### PR TITLE
Streaming Api now available with both POST and GET request methods

### PR DESCRIPTION
**Pull request by gabfusi**
A post request can avoid the common 2000 characters url length limit.
It is useful if you need to request a very long list of hashtags or twitter ids.

### CODE REVIEW

**Comment by desmondmorris** [comment]
@gabfusi perhaps the better solution would be to just default to `POST` always?

Is there a link documenting this change in the Twitter API?

**Comment by desmondmorris** [comment]
I found the link - https://dev.twitter.com/streaming/reference/post/statuses/filter.  Looks like its only documented for the public API (not site and user).  If this is the case, we would not be able to default to `POST` as I suggested above.

**Comment by gabfusi** [comment]
@desmondmorris yes, that's the case. 
My approach was quick and rough, but that script is on production right now and works well.
How about adding an additional method to perform post requests?

**Comment by desmondmorris** [comment]
Closing as this pr would rename the npm package.  These changes have landed in @gabfusi's fork.

**Pull request closed without merging**
