### PR TITLE
pass only one error if error happens, fix #100

### LINKED ISSUE #100: err is an array, and not single error
I have such code:

```
  client.get('/users/show.json', options, function (err, info, raw) {
    console.log(err);
    console.log(err.message);
```

And here is a log:
```
[ { code: 135, message: 'Timestamp out of bounds.' } ]
undefined
```

why err is an array?

### PR DESCRIPTION
**Pull request by iamstarkov**
as titled and checked with my [get-tweets](https://www.npmjs.com/package/get-tweets) package

### CODE REVIEW

**Comment by iamstarkov** [comment]
@desmondmorris can I ask you about code-review for this patch?

**Comment by desmondmorris** [comment]
Thanks @iamstarkov.  I do still think, we may want to defer error parsing to client as per that document, it does not actually say that there can only be a single error delivered in that array, it just shows an example where it does.  There is also language there that implies that the error response could be unstructured:

> Error responses are served with a non-200-series HTTP code. Usually a JSON response will be attached, but some errors will respond with different kinds of body. In these circumstances where a response struture cannot be parsed, consider the HTTP code’s core meaning to take precedence. For instance, you may occaisionally see a HTTP 404 along with a HTML response. In this case, it’s safe to assume that the content cannot be found (HTTP 404 means “Not Found”).
> https://dev.twitter.com/ads/basics/response-codes#Error+Response+Structure

I am just trying to be cautious here as this is a breaking change.

@roach any thoughts/insight here?
Original issue: https://github.com/desmondmorris/node-twitter/issues/100

**Comment by iamstarkov** [comment]
asked about multiply errors in dev forum https://twittercommunity.com/t/array-of-errors-in-error-codes-responses/49286?u=iamstarkov

**Comment by iamstarkov** [comment]
I got reply from twitter staff and it seems to be there is a situation, where array can has more than one error =(

```
"errors": [
    {
      "code": "INVALID",
      "message": "LineItems with different placement types are not allowed inside a campaign : 3222623",
      "attribute": "placement_type"
    },
    {
      "code": "INVALID",
      "message": "Line items with different objectives are not allowed under the same campaign (campaign_id=3222623)",
      "attribute": "objective"
    }
  ],
  "request": {
    "params": {
      "placements": [
        "ALL_ON_TWITTER"
      ],
      "bid_amount_local_micro": 350000,
      "product_type": "PROMOTED_TWEETS",
      "objective": "TWEET_ENGAGEMENTS",
      "account_id": "5gvk9h",
      "include_sentiment": "ALL",
      "campaign_id": "1x2lb"
    }
  }
}
```

**Comment by iamstarkov** [comment]
suggesting new pull-request with

    data.errors = data.errors.map(err => new Error(`Status Code ${error.code}:  ${error.message}`))

and changing docs to show that passed errors can be array instead of single error

**Comment by desmondmorris** [comment]
@iamstarkov thanks for digging into this.  +1 to your suggested solution.

**Comment by iamstarkov** [comment]
while, im not implement it, i want to ask you as a maintainer one more question. this change seems to be breaking change (somebody prob already relying on array of plain error object). is it acceptable or it doesnt worth it?

**Comment by iamstarkov** [comment]
After more work on twitter related modules, I strictly convinced that array of errors is the worst thing about this situation. I faced it so many times, since 5 august. Also, I’m sold with "Worst case is there are more than one error and the first request you see error A, fix it for the second request and then see error B." and don’t sold with official answer "it can happen in real world", because:

1) sure it can, but then you just need to fix one issue after another
2) while its okay for api, its not okay for nodejs library, because everybody relies on one error.

> Special cases aren't special enough to break the rules.
> — The Zen of Python, https://www.python.org/dev/peps/pep-0020/

as a summary I want to suggest to merge this pull-request and release new major version. What do you think?

**Comment by iamstarkov** [comment]
@desmondmorris what do you think about?

**Comment by iamstarkov** [comment]
@desmondmorris polite ping)

**Comment by iamstarkov** [comment]
hi, should I close it?

**Comment by desmondmorris** [comment]
@iamstarkov sorry for the delay.  I think your argument here is def worth the consideration.  I will take a look at this.

**Comment by iamstarkov** [comment]
@desmondmorris it’s okay. hopefully, you will have time for this pull-request now.

waiting to develop bunch of new modules dependent on node-twitter this weekend or definitely in the start of next week

**Comment by iamstarkov** [comment]
any news? =)

**Comment by iamstarkov** [comment]
for now I switched my packages to [twit](https://www.npmjs.com/package/twit) — it handles errors in proper way

**Comment by iamstarkov** [comment]
okay

**Pull request closed without merging**
